name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        netsh advfirewall firewall add rule name="RDP-Tailscale" dir=in action=allow protocol=TCP localport=3389
        Restart-Service -Name TermService -Force

    - name: Create RDP User with Secure Password
      run: |
        $password = "Rdp@123456"
        $securePass = ConvertTo-SecureString $password -AsPlainText -Force

        New-LocalUser "RDP" -Password $securePass -AccountNeverExpires
        Add-LocalGroupMember -Group "Administrators" -Member "RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"

        echo "RDP_USER=RDP" >> $env:GITHUB_ENV
        echo "RDP_PASS=$password" >> $env:GITHUB_ENV


    - name: Install Tailscale
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
        Start-Process tailscale.exe -ArgumentList "/silent" -Wait

    - name: Connect Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey tskey-auth-kG24ineNPw11CNTRL-eHHZMqHPJ17bzeSCHpF827VrdqVFXo6c --hostname github-rdp

    - name: Show RDP Details
      run: |
        $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        echo "===================================="
        echo "RDP ACCESS READY"
        echo "IP: $ip"
        echo "Username: $env:RDP_USER"
        echo "Password: $env:RDP_PASS"
        echo "===================================="

    - name: Keep RDP Alive
      run: |
        Write-Host "RDP running..."
        while ($true) { Start-Sleep -Seconds 300 }
